# Generated by Django 3.1.8 on 2021-05-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myjournal', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
