# Generated by Django 3.1.8 on 2021-04-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default.png', upload_to='media/myfeed'),
        ),
    ]
